sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t satyadev15/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true satyadev15/docker-react npm run test